# -*- coding: utf-8 -*-
"""11399_Greedy_ATM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bAnxlNr5qIMFi7zJfV1vjul9hF2LRLgm
"""

n = int(input())
ptime = list(map(int, input().split()))

ptime.sort()

time = 0
sum = 0
for i in range(n):
    time += ptime[i]
    sum += time 

print(sum)

import numpy as np

def quicksort(ptime):
    equal_,small_, bigger_ = [], [], []
    k = np.random.randint(n)

    pivot = ptime[k]
    ptime[k] = ptime[0]
    ptime[0] = pivot

    for i in range(len(ptime)):
        if pivot > ptime[i]:
            small_.append(ptime[i])
        elif pivot < ptime[i]:
            bigger_.append(ptime[i])
        else:
            equal_.append(ptime[i])

    return small_ + equal_ + bigger_ 

quicksort(ptime)