# -*- coding: utf-8 -*-
"""2839_Greedy_설탕배달

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bAnxlNr5qIMFi7zJfV1vjul9hF2LRLgm
"""

N = int(input())

kg_3 = 0
kg_5 = 0
total = 0

while N >= 5: # N의 무게가 5킬로그램이 넘었을 경우에 루프 실행
    if N <= 12 and N%5 != 0: # 12 이하의 수 중 5로 나누어 떨어지지 않는 수들에서 break
        break
    else:
        N -= 5
        kg_5 += 1
        
while N >= 3: # N의 무게가 3킬로그램이 넘거나 같을 경우 루프 실행
    if (N-5)%3 == 0: # 앞선 루프에서 break했지만 5로 한번 뺄셈을 했을 때 3으로 나누어 떨어지는 경우
        N -= 5
        kg_5 += 1
    else:
        N -= 3
        kg_3 += 1

total = kg_5 + kg_3

if N != 0:
    total = -1
        
print(total)